### ISSUE TITLE
vartiste-toolkit.js:2 WebSocket connection to wss://127.0.0.1:6436/v6.json' failed: 

### ISSUE THREAD

**Issue by quantumalchemy** [zach-capalbo/vartiste#12]
Hi - first Great project!
searching your docs cant find anything on why the script is making call to --> wss://127.0.0.1:6436/v6.json
obvious wanting to read the data there
Doesn't seem to break anything since im just using the drawing components. no other errors.

Anyway to disable the call from a config or setting?
- Thanks!

**Comment by zach-capalbo** [comment]
Hi, thanks!

The call to `wss://127.0.0.1:6436/v6.json` is attempting to connect to Leap Motion hand tracking (more info here: https://github.com/leapmotion/leapjs ), and the error just means that leap motion hand-tracking for web apps is unavailable.

Unfortunately, I haven't found a way to suppress that error, or check for the controller without the websockets connection. 

However, you avoid the error by disabling hand-tracking components completely by adding

```javascript
  <script>VARTISTE_TOOLKIT = {
      excludeFiles: ['leap-hand', 'hand-tracking']
    }</script>
```

**before** you include `aframe-vartiste-toolkit.js`


I think in a future version I'll try to add that to the console output or something so that people won't have to worry about it.

**Comment by quantumalchemy** [comment]
Great thanks!
